flowchart TB

J["Security & Subject Rules"]:::main
J --> J1["No ready-made nginx image"]
J1 --> J2["No ready-made wordpress image"]
J2 --> J3["No ready-made mariadb image"]
J3 --> J4["No latest tag"]
J4 --> J5["No host network"]
J5 --> J6["No passwords inside Dockerfiles"]
J6 --> J7["Use .env for credentials"]
J7 --> J8["Only HTTPS allowed"]
J8 --> J9["Database not exposed to host"]
J9 --> J10["WordPress admin username must not contain admin"]

classDef main fill:#111827,color:#ffffff,stroke:#38bdf8,stroke-width:2px;
